included:
  - ../

excluded:
  - Pods

opt_in_rules:
  - array_init
  - function_default_parameter_at_end
  - legacy_random
  - empty_count


disabled_rules:
  - trailing_whitespace
  - void_function_in_ternary

force_cast: warning # Alerta para uso de `as!`
force_try: warning # Alerta para uso de `try!`
empty_count: warning # Alerta para uso de `array.count == 0`

line_length: 180 # Máximo de caracteres por linha

cyclomatic_complexity:
  warning: 15
  error: 40

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 1
  max_length:
    warning: 80
    error: 100
  excluded:
    - iPhone

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 60
    error: 100
  excluded:
    - _id
    - URL
    - Key

function_body_length:
  warning: 100
  error: 100

reporter: "xcode"
