# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Multiverse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  # Pods for Multiverse

  pod 'SDWebImage'
  pod 'SwiftLint'

  target 'MultiverseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultiverseUITests' do
    # Pods for testing
  end

end
